### PR TITLE
Make sqlx.scanAll() publicly available as sqlx.ScanAll()

### PR DESCRIPTION
**Pull request by chr4**
This is useful in some cases, e.g. when parsing multiple rows into an array of structs using
sqlx.NamedQuery().

```go
func GetWithNamedQuery(db sqlx.DB, target interface{}, query string, arg interface{}) (err error) {
    rows, err = db.NamedQuery(query, arg)
    if err != nil {
        return
    }

    // If something happens here, we want to make sure the rows are closed
    defer rows.Close()

    // This depends on sqlx.ScanAll() being an exported function.
    err = sqlx.ScanAll(rows, obj, false)
    return
}
```

The caller could then build (SQL injection secure) queries using something like this:

```go
// The id is mandatory
query := []string{`SELECT * FROM table WHERE id=:id`}

// Only filter for type if type was given
if where.Type != "" {
    query = append(query, `AND type=:type`)
}

// Only filter for state if state was given
if where.State != "" {
    query = append(query, `AND state=:state`)
}

// Order results
query = append(query, `ORDER BY created_at ASC`)
err = sql.NamedQuery(db, &contributions, strings.Join(query, " "), where)
```

I'm not sure whether this is the best option to build more dynamic queries, but I couldn't find a better option yet. Hints apprechiated.

### CODE REVIEW

**Comment by jmoiron** [comment]
I've felt that the solution to exposing more of this type of stuff or adding more `Named*` things to the DB object was to encourage use of `PrepareNamed`, which has `Select` et al.  I think that's sufficient for all use cases where you might want `ScanAll`.

**Comment by chr4** [comment]
Thanks for your response!
I tried using `PrepareNamed()` in the example above, but I couldn't find a clean solution when trying to build more dynamic queries (like in the example above). Could you give me a hint/ an example how the problem could be solved using `PrepareNamed()` only?

The only/ cleanest thing I came up with is using `ScanAll()`, but I might have overlooked something.

**Comment by jmoiron** [comment]
If you use `PrepareNamed`, then you can use `Select` to get the equivalent of `ScanAll`:

```go
stmt, err := db.PrepareNamed(`...`)
// handle err
var objs []MyObj
stmt.Select(&objs, where)
```

Please re-open if this isn't what you wanted!

**Comment by chr4** [comment]
Thanks! This works great.

**Pull request closed without merging**
