### PR TITLE
Support sql.Conn

### PR DESCRIPTION
**Pull request by siddontang**
Golang has already supported Conn https://golang.org/pkg/database/sql/#Conn, we can wrap it in sqlx too. 

PTAL @jmoiron

### CODE REVIEW

**Comment by siddontang** [comment]
The CI raised `pq: column "a" does not exist` error, seem not relevant to this change.

**Comment by jmoiron** [comment]
This looks great.  I might need to build tag this for 1.12 users, since I have said I'd support the past two versions, and I think a lot of large codebases have not been able to get onto modules yet.  

I'll try to get to the bottom of the test failures.

**Comment by siddontang** [comment]
Thanks @jmoiron 

I guess Go 1.12 has already supported sql.Conn, if not, maybe we can use a build flag to control it.

**Comment by siddontang** [comment]
@jmoiron 

I have already fixed the CI, PTAL again.

**Comment by siddontang** [comment]
Friendly ping @jmoiron

**Comment by muharem** [comment]
@siddontang 
Hey, thank you for the PR.
What do you think about adding support of methods which provides named arguments, like DBx provides (NamedQuery, NamedExec ...)?

**Comment by jmoiron** [comment]
Now that 1.12 is 2 versions old I'm going to just merge this directly into the main branch in anticipation  of a new versioned release.  Just working through an issue I'm having with the mysql driver in the tests.

**Comment by jmoiron** [comment]
This is now fully merged, the issue was unrelated to this change and fixed by a previous merge.

**Pull request merged**
