### PR TITLE
Add experimental support for 1.8's new Context based database/sql functions

### PR DESCRIPTION
**Pull request by wyattjoh**
This PR adds experimental support for Go 1.8's new `context.Context` based functions. Tests have been duplicated for the Context based functions to bring them up to parity.

### CODE REVIEW

**Comment by dlsniper** [comment]
@jmoiron what do you think it's needed to get this merged? I'd be happy to help testing out if needed. Thank you!

**Comment by gpopovic** [comment]
@jmoiron can you take a look at this?

**Comment by c4milo** [comment]
nice! I created https://github.com/jmoiron/sqlx/issues/278 before finding this PR. I would leave it open anyways.

**Comment by husio** [comment]
Is there a reason why transaction does not support `XxxContext` methods or this is just missing functionality that is waiting to be implemented?

**Comment by gpopovic** [comment]
@husio  i already created an issue for that here #286

**Pull request merged**
