### PR TITLE
Add support for omitempty

### PR DESCRIPTION
**Pull request by adilhafeez**
This is for following issue,
https://github.com/jmoiron/sqlx/issues/279

### CODE REVIEW

**Comment by adilhafeez** [comment]
@jmoiron ^

**Comment by Willux** [comment]
Is this going to be merged anytime?

**Comment by reallyroy** [comment]
Is there any plan to support "omitempty" for sqlx?

**Comment by dlsniper** [comment]
Hello, @ardan-bkennedy, and I recently stepped in to help maintain this project.
We are sorting the opened issues and pull requests and would like to know if you still NEED this merged.
If yes, then can you please rebase it?
Thank you for your contribution.

**Pull request closed without merging**
