### PR TITLE
Fix batch INSERT when using ON CONFLICT

### PR DESCRIPTION
**Pull request by bretep**
Fixes issue #505

### CODE REVIEW

**Comment by bretep** [comment]
The failure is unrelated to this commit and fails only for go1.8

**Comment by bretep** [comment]
@hmgle are you able to merge this?

**Comment by bretep** [comment]
I've been using this patch for the past 20 or so days. It's been working as expected. Thanks @hmgle

**Comment by hmgle** [comment]
@jmoiron Could you please review and handle this pr? Thanks.

**Comment by bretep** [comment]
Thanks @hmgle for pingin @jmoiron 

@jmoiron Hopefully we can get this committed soon so that I don't have to maintain a fork. :) Please let me know if I need to take any additional steps to get this PR accepted.

**Comment by jmoiron** [comment]
The 1.8 failure is due to the mysql driver dropping support for 1.8;  I believe my backwards compatability guarantee also drops 1.8 so I'll remove it from the testing matrix instead of trying to fix it.

Additionally, since there has been no tagged release yet for this feature (I want to get more time to live with it), I don't mind removing an exported identifier...  in fact, I prefer it, it wasn't necessary to export in the first place.

**Comment by bretep** [comment]
Thank you!

**Pull request merged**
