### PR TITLE
Make Select reset slice length

### PR DESCRIPTION
**Pull request by gayoungpark**
Fixes issue #744.

### CODE REVIEW

**Comment by cespare** [comment]
@jmoiron WDYT about merging this? We've been using it in production for a while and it has been a very useful change for us.

**Comment by jmoiron** [comment]
v1.3.5

**Comment by cespare** [comment]
Thanks @jmoiron !

**Comment by cpuschma** [comment]
Thank you @jmoiron for still caring about the repository ❤️

**Comment by benCoomes** [comment]
👋 Hi @jmoiron! I recently updated my application to 1.3.5 and noticed my tests were failing due to this change. I guess I'm one of the victims of Hyrum's law. 🥲 

Since this is a breaking change, would you consider making the behavior opt-in? Or, at the very least, updating the major version. Folks won't be expecting a change like this on a patch update.

**Pull request merged**
